export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_ERROR   = 'SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_CLEAR   = 'SEARCH_MOVIE_CLEAR';

export const MOVIE_DETAILS_PENDING = 'MOVIE_DETAILS_PENDING';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_ERROR   = 'MOVIE_DETAILS_ERROR';


export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR   = 'LOGIN_USER_ERROR';