export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_ERROR   = 'SEARCH_MOVIE_ERROR';

export const MOVIE_DETAILS_PENDING = 'MOVIE_DETAILS_PENDING';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_ERROR   = 'MOVIE_DETAILS_ERROR';
